config/routes.rb
No::Application.routes.draw do
  resources :books
  resources :authors

  root 'books#index'

end

app/models/ab.rb
class Ab < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :abs
	has_many :books,:through=>:abs

	validates :name,:presence=>{:message=>'no puede ser vacio'}
	validates :check,:presence=>{:message=>'no puede ser vacio'}
	validates :check,:numericality=>{:only_integer=>true,:less_than_or_equal_to=>1,:message=>'Solo puede ser 1 o 0	'}
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :abs
  has_many :authors,:through=>:abs

  validates :title, :presence=>{:message=>'no puede ser blanco'}
  validates :year, :presence=>{:message=>'la fecha es obligatoria'}
  validates :year, :numericality=>{:message=>'solo numeros'}
  validates :year, :length => {:maximum=>4,:message=>'es demaciado largo'}
  validates :year, :length => {:minimum=>1,:message=>'es demaciado corto'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author,:only=>[:show,:edit,:update,:destroy]
  def index
  	@authors = Author.all
  end
  def show
  end
  def edit
  end
  def update
    if @author.update(author_params)
      redirect_to @author,:notice=>'Author editado con exito'
    else
      render  'edit'
    end
  end
  def new
    @author = Author.new
  end
  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author,:notice=> 'Author creado con exito'
    else
      render 'new'
    end
  end
  def destroy
    @author.destroy
    redirect_to authors_path,:notice=>'Author eliminado con exito'
  end
  private
  def set_author
  	@author = Author.find_by_id(params[:id])
  end
  def author_params
    params.require(:author).permit(:name,:check)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only:[:show,:edit,:update,:destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book,:notice=>'el libro fue editado con exito'
    else
      render 'edit'
    end
  end

  def new
    @book = Book.new()
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book,:notice=>'El libro fue creado con exito'
    else
      render 'new'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path,:notice=>'El libro fue eliminado'
  end

  private

  def get_authors_ids
    params.require(:book).require(:authors).permit(author_id: [])[:author_id]
  end

  def set_book
    @book = Book.find_by_id(params[:id])
  end

  def book_params
    params.require(:book).permit(:title,:year,author_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%=form_for @author do |f|%>
<%if @author.errors['name'].any?%>
	<%=@author.errors['name'][0]%>
<%end%>
<%=f.label :name%>
<%=f.text_field :name%>
<br>
<%if @author.errors['check'].any?%>
	<%=@author.errors['check'][0]%>
<%end%>
<%=f.label :check %>
<%=f.number_field :check%>
<br>
<%=f.submit 'enviar' %>
<%end%>

app/views/authors/edit.html.erb
<h1>Editando a <%=@author.name%></h1>
<%=render 'form'%>
<%=link_to 'listado',authors_path%>
<%=link_to 'mostrar',@author%>

app/views/authors/index.html.erb
<%if flash[:notice]%>
<%=flash[:notice]%>
<%end%>
<table border="1">
<tr>
	<td>id</td>
	<td>name</td>
	<td>ver</td>
	<td>edit</td>
	<td>eliminar</td>
</tr>
<%@authors.each do |author|%>
<tr>
	<td><%=author.id%></td>
	<td><%=author.name%></td>
	<td><%=link_to 'ver',author%></td>
	<td><%=link_to 'edit',edit_author_path(author)%></td>
	<td><%=link_to 'destroy',author_path(author),:method=>:delete,:confirm=>'are you sure?'%></td>
</tr>
<%end%>
</table>
<br>
<%=link_to 'crear author',new_author_path%>

app/views/authors/new.html.erb
<h1>Crear author</h1>
<%=render 'form'%>
<%=link_to 'back',authors_path%>

app/views/authors/show.html.erb
<%if flash[:notice]%>
<%= flash[:notice]%>
<%end%>
<h1><%=@author.name%></h1>
<%if @author.check==1%>
	Author validado
<%else%>
    Author no validado
<%end%>
<br>
<br>
<%=link_to 'back',authors_path%>
<%=link_to 'edit',edit_author_path(@author)%>

app/views/books/_form.html.erb
<%if flash[:notice]%>
<%= flash[:notice]%>
<%end%>
<%=form_for @book do |f|%>
<%if @book.errors['title'].any?%><%=@book.errors['title'][0]%> <%end%>
<%=f.label 'title'%>
<%=f.text_field 'title'%>
<br>
<%if @book.errors['year'].any?%><%=@book.errors['year'][0]%> <%end%>
<%=f.label 'year'%>
<%=f.number_field 'year'%>
<br>

<%= f.select :author_ids, Author.pluck(:name, :id) ,{},{:multiple=>true}%>
<br>
<%=f.submit 'enviar' %>
<%end%>

app/views/books/edit.html.erb
<h1>Editar Libro</h1>
<%=render 'form' %>

app/views/books/index.html.erb
<h1>Libros</h1>	
<%if flash[:notice] %>
<%=flash[:notice]%>
<%end%>
<table border='1'>
	<tr>
		<td>num</td>
		<td>Title</td>
		<td>Year</td>
		<td>ver</td>
		<td>editar</td>
		<td>eliminar</td>
		<td>author</td>
	</tr>
	<% @books.each do |b| %>
	<tr>
		<td><%=b.id%></td>
		<td><%=b.title%></td>
		<td><%=b.year%></td>
		<td><%=link_to 'Ver',book_path(b)%></td>
		<td><%=link_to 'editar',edit_book_path(b)%></td>
		<td><%=link_to 'eliminar',book_path(b),:method=>:delete,:confirm=>'Estás seguro?'%></td>
	</tr>
	<%end%>
</table>
<%=link_to 'create',new_book_path,:style=>'text_decoration:none;color:red'%>

app/views/books/new.html.erb
<h1>Nuevo libro</h1>
<%=render 'form'%>

app/views/books/show.html.erb
<%if flash[:notice]%>
<%=flash[:notice]%>
<%end%>
<h1><%=@book.title%></h1>
<p>Año: <%=@book.year%></p>
<%=link_to 'edit',edit_book_path(@book)%>
<%=link_to 'list',books_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>No</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>